// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventList {
    #[prost(message, optional, tag="1")]
    pub clock: ::core::option::Option<super::super::v1::Clock>,
    #[prost(message, repeated, tag="2")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(string, tag="1")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub event: ::core::option::Option<super::super::super::cosmos::r#type::v2::Event>,
}
// @@protoc_insertion_point(module)
